### ISSUE TITLE
Remove nilearn package from anaconda.org conda-forge channel

### ISSUE THREAD

**Issue by lesteve** [conda-forge/nilearn-feedstock#14]
What is the procedure to remove packages from anaconda.org conda-forge channel? I googled a bit and found no obvious answer I am afraid.

The motivation behind the question: we are encouraging users to install nilearn with pip. We have not been very good at updating the nilearn recipe on each nilearn release and at the moment we do not think it is worth the effort (even if the effort is quite small) to have nilearn available on conda-forge.

ping @pelson.

**Comment by ocefpaf** [comment]
There is no need to remove, just abandon it and users will be able figure out that they either need to pick up the feedstock as maintainers or use `pip`.

BTW I have a use for `nilearn` so I can pick it up. Should I remove you from the maintainer list or do you still want to be there?

**Comment by lesteve** [comment]
> There is no need to remove, just abandon it and users will be able figure out that they either need to pick up the feedstock as maintainers or use pip.

It is probably true for advanced users but not for a significant portion of the users nilearn is trying to target ...

> BTW I have a use for nilearn so I can pick it up. Should I remove you from the maintainer list or do you still want to be there?

Thanks a lot for proposing your help! I don't mind staying a maintainer. Feel free to open a PR where you add your name as maintainer. While you are at it, if you could add @GaelVaroquaux as a maintainer it would be great.

If you want to rerender with a more recent of conda-smithy or something that is more in line with the conda-forge best practices, be my guest too!

**Comment by lesteve** [comment]
I just saw your PR now. Great thanks a lot!

**Comment by lesteve** [comment]
I'll open another PR to add @GaelVaroquaux as a maintainer.

**Comment by ocefpaf** [comment]
> It is probably true for advanced users but not for a significant portion of the users nilearn is trying to target ...

That is the beauty of `conda-forge` we need only 1 users willing to do it so many can enjoy the results.

> Thanks a lot for proposing your help! I don't mind staying a maintainer.

Not at all!

> Feel free to open a PR where you add your name as maintainer. While you are at it, if you could add @GaelVaroquaux as a maintainer it would be great. If you want to rerender with a more recent of conda-smithy or something that is more in line with the conda-forge best practices, be my guest too!

Done and done in #15 

As soon as @GaelVaroquaux gives his :+1: I'll add him too.

**Comment by GaelVaroquaux** [comment]
@ocefpaf : that's awesome. Open source magic! Thanks a lot for stepping up, and happy to have you on board!!!

Yes, I think that adding me is a good idea. I'll probably not ever do anything, because I am drowning with stuff, but just in case, as I am one of the head honchos of nilearn and likely to stay around, it's useful to have me with the rights.
