### ISSUE TITLE
nilearn depends on setuptools

### ISSUE THREAD

**Issue by pelson** [conda-forge/nilearn-feedstock#5]
Looks like this package depends on setuptools, and that isn't expressed in the recipe.

This was identified in #4 where the builds were failing. We have recently improved the conda-forge build image so that we do not include setuptools by default, which is why this feedstock is now failing.

**Comment by lesteve** [comment]
Thanks for pointing out the issue, I just pushed a change to master: https://github.com/conda-forge/nilearn-feedstock/commit/9c7c8787356fc9e2d6848fb7255b1e823080a8e6.

**Comment by jakirkham** [comment]
So that change should really come with a build number bump and would be much better as a PR to allow for engagement and better tracking.

**Comment by lesteve** [comment]
I guess I did not want a new package to be uploaded to conda-forge since the nilearn version has not changed. That's what a build number bump would do I presume? Sorry very new to conda-forge, but I would be more than happy to learn more, is there some reference material to get started?
